# 01 - Data Exploration

## Objective
Understand dataset structure, quality, missing values, and basic patterns before preprocessing or modeling.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv("./../data/openaq_location_6358.csv")

In [10]:
df2 = pd.read_csv("./../data/openaq_location_6358_set2.csv")

In [11]:
df.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6358,"Mandir Marg, New Delhi - DPCC",pm10,269.0,µg/m³,2026-01-01T00:15:00Z,2026-01-01T05:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
1,6358,"Mandir Marg, New Delhi - DPCC",pm10,285.0,µg/m³,2026-01-01T00:30:00Z,2026-01-01T06:00:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
2,6358,"Mandir Marg, New Delhi - DPCC",pm10,285.0,µg/m³,2026-01-01T00:45:00Z,2026-01-01T06:15:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
3,6358,"Mandir Marg, New Delhi - DPCC",pm10,285.0,µg/m³,2026-01-01T01:00:00Z,2026-01-01T06:30:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
4,6358,"Mandir Marg, New Delhi - DPCC",pm10,285.0,µg/m³,2026-01-01T01:15:00Z,2026-01-01T06:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB

In [12]:
df2.head()

,location_id,location_name,parameter,value,unit,datetimeUtc,datetimeLocal,timezone,latitude,longitude,country_iso,isMobile,isMonitor,owner_name,provider
0,6358,"Mandir Marg, New Delhi - DPCC",co,3.39,ppb,2026-01-01T00:15:00Z,2026-01-01T05:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
1,6358,"Mandir Marg, New Delhi - DPCC",co,3.38,ppb,2026-01-01T00:30:00Z,2026-01-01T06:00:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
2,6358,"Mandir Marg, New Delhi - DPCC",co,3.29,ppb,2026-01-01T00:45:00Z,2026-01-01T06:15:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
3,6358,"Mandir Marg, New Delhi - DPCC",co,3.18,ppb,2026-01-01T01:00:00Z,2026-01-01T06:30:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB
4,6358,"Mandir Marg, New Delhi - DPCC",co,3.16,ppb,2026-01-01T01:15:00Z,2026-01-01T06:45:00+05:30,Asia/Kolkata,28.636429,77.201067,NaN,NaN,NaN,Delhi Pollution Control Committee,CPCB